//
// Created by Ilshat on 24.11.2018.
//

#ifndef COMPILERS_PROJECT_TYPE_H
#define COMPILERS_PROJECT_TYPE_H

enum TYPE {
    STRING, REGISTER_VALUE, EQUAL, STAR, COLON, SEMICOLON, IF, GOTO,
    QUESTION, PLUS, MINUS, AND, NUMBER, GREATER, LESS, OR, XOR, SKIP, STOP
};

#endif //COMPILERS_PROJECT_TYPE_H
